version: '3.8'

services:
  workday-scraper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: workday-scraper
    restart: unless-stopped
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - DB_FILE=/app/data/workday_jobs.db
      - LOG_FILE=/app/logs/workday_scraper.log
      - LOG_LEVEL=INFO
      - CONFIG_FILE=autodesk.txt  # Default config file to use for scheduled runs
      - TZ=America/Los_Angeles    # Set your timezone here
    volumes:
      - ./data:/app/data        # Database storage
      - ./configs:/app/configs  # Configuration files
      - ./logs:/app/logs        # Log files
    networks:
      - workday-net
    healthcheck:
      test: ["CMD", "python", "-c", "import os; exit(0 if os.path.exists('/app/data/workday_jobs.db') else 1)"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  workday-net:
    driver: bridge