name: Run Workday Scraper

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

env:
  CHANGES: True

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run
      run: python3 workday.py
    - name: Rename
      run: mv rss.xml rss-chris.xml
    - name: Stash changes
      run: |
        git stash || echo "No changes!" && echo "CHANGES=False" >> $GITHUB_ENV
    - name: Push to rss
      if: env.CHANGES
      run: |
        git branch
        git checkout rss
        git stash apply
        git config --global user.name "${GITHUB_ACTOR}"
        git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git add .
        git commit -m "Run Workday Scraper"
        git push
